glib: fix compile break because unused_data
In file included from /home/djz/workspace/test/vela/nuttx/include/stdint.h:33,
                 from ./config.h:380,
                 from glib/glib/gmessages.c:171:
glib/glib/gmessages.c: In function ‘g_log_default_handler’:
glib/glib/gmessages.c:3271:64: error: expected expression before ‘__attribute__’
 3271 |       _g_log_fallback_handler (log_domain, log_level, message, unused_data);
      |                                                                ^~~~~~~~~~~

Signed-off-by: dongjiuzhu1 <dongjiuzhu1@xiaomi.com>